import { contentInterface } from './Model'

export const systemManageList:contentInterface={
  title:"系统管理",
  list:[
    {
      name: "通知中心",
      router:''
    },
    {
      name: "用户管理",

      router:''
    },
    {
      name: "角色管理",
      router:''
    },
    {
      name:  "菜单管理",

      router:''
    },
    {
      name:     "部门管理",
      router:''
    },
    {
      name:    "岗位管理",
      router:''
    },
    {
      name:     "字典管理",
      router:''
    },
    {
      name:     "系统日志",
      router:''
    },
    {
      name:     "退出系统",
      router:''
    },
    {
      name: "通知中心",
      router:''
    },
  ]
}

export const dataManageList:contentInterface={
  title:'基础数据维护',
  list:[
    {name:'课程维护',router:''},
    {name:'活动管理',router:''},
  ]
}

export const customManageList:contentInterface={
  title:'客户管理',
  list:[
    {name:'商机',router:''},
    {name:'公海池',router:''}
  ]
}

export const countManageList:contentInterface={
  title:'统计管理',
  list:[
    {name:'客户统计',router:''},
    {name:'销售统计',router:''},
    {name:'线索统计',router:''},
    {name:'渠道统计',router:''},
    {name:'线索管理',router:''}
  ]
}

export const orderManageList:contentInterface={
  title:'工单管理',
  list:[
    {name:'工单管理',router:''}
  ]
}

export const contactManageList:contentInterface={
  title:'合同管理',
  list:[
    {name:'合同管理',router:''}
  ]
}